# Sections content configuration file
## 
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  image: "assets/img/man2.jpg"
  text: "<p>Hello! I’m Obreja Adrian. Web designer from EU, with passion for new technologies. Love to work on front-end, make site design, building them and satisfied when pixels come to “life”. Also I love Drupal, that have a special place in my heart. Clean and minimalist web design, clean code and fast loading websites are three of my base principles.</p>"
  list:
    # - label: "Age"
    #   value: "46"

    - label: "Residence"
      value: "Romania, Moldova"

    - label: "Freelance"
      value: "Available" #nonavailable

    - label: "Address"
      value: "heart of Europe"

    - label: "Phone IT"
      value: "+39 38-902-32-042"

    - label: "E-mail"
      value: "andy@da.md"

    - label: "Phone UK"
      value: "+44 74-888-11-737"

  download:
    text: "Download CV"
    link: "https://www.dropbox.com/s/k06agipxn94kiz6/Resume%20-%20Andy.pdf?dl=0"

### Services [ services ]
services:
  title: "Services"
  items:
    - icon: "fas fa-code"
      name: "Web Development"
      text: "Modern and mobile-ready website that will help you reach all of your marketing."

    - icon: "fab fa-drupal"   
      name: "Drupal and e-commerce"
      text: "Unique customer experiences, complex checkout flows, and deep integrations into payment and fulfillment vendors."

    - icon: "fas fa-ad"
      name: "Advetising"
      text: "Advertising services include television, radio, print, mail, and web apps."

    - icon: "fas fa-gamepad"
      name: "Game Development"
      text: "Developing memorable and unique mobile android, ios and video games."

    - icon: "fas fa-camera"
      name: "Photography"
      text: "Our in-house photography services team made up of professional photographers."

    - icon: "fas fa-mobile-alt"
      name: "Android Application"
      text: "Games, playing music, handle network transactions, interacting content etc."
      
# ### Pricing [ pricing ]
# pricing:
#   title: "Pricing"
#   items:
#     - icon: "fas fa-star"
#       name: "Basic"
#       price: "39"
#       price_before: "$"
#       price_after: "hour"
#       list:
#         - value: "Web Development"
#           disable: "no"
#         - value: "Advetising"
#           disable: "no"
#         - value: "Game Development"
#           disable: "no"
#         - value: "Music Writing"
#           disable: "yes"
#         - value: "Photography"
#           disable: "yes"
#       button: "Buy Now"
#       link: "contact/"
          
#     - icon: "fas fa-rocket"
#       name: "Premium"
#       price: "59"
#       price_before: "$"
#       price_after: "hour"
#       list:
#         - value: "Web Development"
#           disable: "no"
#         - value: "Advetising"
#           disable: "no"
#         - value: "Game Development"
#           disable: "no"
#         - value: "Music Writing"
#           disable: "no"
#         - value: "Photography"
#           disable: "no"
#       button: "Buy Now"
#       link: "contact/"

### Resume [ resume ]
resume:
  experience:
    title: "Experience"
    items:
      - year: "2019 - Present"
        name: "Freelance | Independent Developer"
        text: "Collaborate with creative and development teams on the execution of ideas."

      - year: "2013 - 2019"
        name: "librarie.md| Project Manager, Founder"
        text: "Technology Company which focuses on e-commerce. Online bookstore for books, ebooks, music, movies & toys."

      - year: "May 2000 - Present"
        name: "DesignART S.R.L | Art Director, Founder"
        text: "Offset & Digital Products, Print Design, Business Marketing Products, Technology, Information and Internet. <br><br>Responsible for maintaining a creative culture, monitoring assigned properties to ensure consistency of creative direction, identity and quality are maintained.
Strong ideas generation, with a commercial focus. Working Experience with printing, publishing, large format media, advertising and marketing communications companies in across EU & Moldova having anchored creative desing of magazines, news papers, directories corporate profiles, branding & marketing campaigns elements including those for events and exhibitions."

      - year: "Sep 1997 - Feb 2000"
        name: "Document's World S.R.L | Director, Co-Founder"
        text: "Offset & Digital Products, Print Design, Business Marketing Products, Technology, Information and Internet."

  education:
    title: "Education"
    items:
      - year: "2022"
        name: "Learning Path : Become a DevOps Engineer : LinkedIn Learning"
        text: "Learning Path that helps you gain skills to work in DevOps. Learn about infrastucture automation, lean and agile transformation, security, monitoring, and site reliability engineering."

      - year: "2020 - Present"
        name: "freeCodeCamp.org | Learn to code for free with millions of other people around the world."
        text: " - Responsive Web Design.<br>
                - JavaScript Algorithms and Data Structures.<br>
                - Front End Development Libraries.<br>
                - Data Visualization with D3.<br>
                - Back End Development and APIs.<br>
                - Scientific Computing with Python."

      - year: "2016 - 2020"
        name: "Drupal 8(9) Enterprise Web Development | Drupalize.Me"
        text: "Leading provider of Drupal training services. Premium online tutorial library that has trusted thousands of individuals and organizations around the world."

      - year: "2015"
        name: "CS50: Introduction to Computer Science | Harvard University"
        text: "An introduction to the intellectual enterprises of computer science and the art of programming."

      - year: "2008"
        name: "Продвинутый HTML и CSS | HTML Academy"
        text: "Знакомство с продвинутыми возможностями HTML: формами, таблицами, элементами для проигрывания медиа. Детальное разборка важных механизмов CSS."

### Skills [ skills ]
skills:
  columns:
    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Design Skills"
      items:
        - label: "Web Design"
          value: "70" #0-100 progress in %

        - label: "Illustrations"
          value: "90" #0-100 progress in %

        - label: "Photoshop"
          value: "75" #0-100 progress in %

        - label: "Graphic Design"
          value: "80" #0-100 progress in %

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Languages Skills"
      items:
        - label: "English"
          value: "80" #0-100 progress in %

        - label: "Romanian"
          value: "100" #0-100 progress in %

        - label: "Italian"
          value: "30" #0-100 progress in %

        - label: "Russian"
          value: "90" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Coding Skills"
      items:
        - label: "Drupal"
          value: "95" #0-100 progress in %

        - label: "PHP/MYSQL"
          value: "75" #0-100 progress in %

        - label: "React,Vue.js / JavaScript"
          value: "85" #0-100 progress in %

        - label: "HTML / CSS"
          value: "90" #0-100 progress in %

    - type: "list" #skills progress type - default, dotted, circles, list
      title: "Knowledge"
      items:
        - label: "Website hosting"
          value: "" #0-100 progress in %

        - label: "iOS and android apps"
          value: "" #0-100 progress in %

        - label: "Create logo design"
          value: "" #0-100 progress in %

        - label: "Design for print"
          value: "" #0-100 progress in %

        - label: "Modern and mobile-ready"
          value: "" #0-100 progress in %

        - label: "Advertising services include"
          value: "" #0-100 progress in %

        - label: "Graphics and animations"
          value: "" #0-100 progress in %

        - label: "Search engine marketing"
          value: "" #0-100 progress in %

### Facts [ facts ]
facts:
  title: "Interests"
  items:
    - icon: "fas fa-baseball-ball"
      name: "Minifootball"
      text: "The term “minifootball” means small sided football open for amateur players. "

    - icon: "fas fa-campground"
      name: "Van Camping"
      text: "If you don't know where you are going, any road will get you there"

    - icon: "fas fa-chess-knight"
      name: "Chess"
      text: "“Chess is a war over the board. The object is to crush the opponent's mind.” – Bobby Fischer"

    - icon: "fas fa-headphones"
      name: "Music"
      text: "One good thing about music, when it hits you, you feel no pain. – Bob Marley"
      
### Team [ team ]
team:
  title: "Cloud Experience"
  items:
    - image: "assets/img/skills/cloud-service_skills.jpg"
      # name: "Alejandro Abeyta"
      # role: "Web Developer"
      # social:
      #   - url: "https://www.pinterest.com/"
      #     icon: "fab fa-pinterest"
      #   - url: "https://www.instagram.com/"
      #     icon: "fab fa-instagram"
      #   - url: "https://dribbble.com/"
      #     icon: "fab fa-dribbble"
          
    - image: "assets/img/skills/programmes_os_skills.jpg"
      # name: "Peter Green"
      # role: "Back-end Developer"
      # social:
      #   - url: "https://www.pinterest.com/"
      #     icon: "fab fa-pinterest"
      #   - url: "https://www.instagram.com/"
      #     icon: "fab fa-instagram"
      #   - url: "https://dribbble.com/"
      #     icon: "fab fa-dribbble"

    - image: "assets/img/skills/technology_skills.jpg"

### Testimonials [ testimonials ]
testimonials:
  title: "Testimonials"
  items:
    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      
    - image: "assets/img/testimonials/rev1.jpg"
      name: "Helen Floyd"
      role: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Clients [ clients ]
clients:
  title: "Clients"
  items:
    - url: "https://www.google.com"
      image: "assets/img/clients/client1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client3.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client4.png"
      
### Custom Text [ text ]
text:
  title: "Custom Text"
  text: "
        <p>
            Now there is more fashion. There is no so-called trends. Now chase after anything not necessary — nor for fashionable color nor the shape, nor for style. Think about the content that you want to invest in a created object, and only then will form. The thing is your spirit. A spirit unlike forms hard copy.
        </p>
        <p>
            Here choose yourself like that, without any looking back, do your personal, home, small fashion, and all will be well.
        </p>
        "

### Contact Info [ contacts-info ]
contacts_info:
  title: "Contacts Info"
  list:
    - label: "Phone"
      icon: "fas fa-phone"
      value: "UK +44 74-888-11-737"

    - label: "Email"
      icon:  "fas fa-envelope"
      value: "<a href='mailto:andy@da.md'>andy@da.md</a>"

    # - label: "Address"
    #   icon: "fas fa-map-marker-alt"
    #   value: "2621 W Pico Blvd, Los Angeles"
    
    - label: "Freelance Available"
      icon: "fas fa-user-tie"
      value: "I am available for freelance hire"

### Contact Form [ contacts-form ]
contacts_form:
  title: "Contact Form"

