# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  logo_text: "Adrian <strong>Obreja</strong>"
  logo_hover_text: "Download <strong>CV</strong>"
  link: "https://www.dropbox.com/s/k06agipxn94kiz6/Resume%20-%20Andy.pdf?dl=0"
  quick_colors: "" # select quick color schemes: "beige", "blue", "brown", "green_light", "green", "orange", "purple", "red", "yellow_light", "yellow". If empty colors taken from _sass/ryancv/settings.scss

### Portfolio Filters Settings
portfolio:
  filters:
    # - name: "Video"
    #   slug: "f-video"

    # - name: "Music"
    #   slug: "f-music"

    - name: "Graphic Design"
      slug: "f-grad"

    - name: "Web Design"
      slug: "f-webd"

    - name: "Branding Desing"
      slug: "f-brand"

    - name: "Mockup"
      slug: "f-mockup"

    - name: "Logo"
      slug: "f-logo"

    - name: "Web Development"
      slug: "f-wdev"

    # - name: "Image"
    #   slug: "f-image"

    # - name: "Gallery"
    #   slug: "f-gallery"

    # - name: "Content"
    #   slug: "f-content"

    # - name: "Links"
    #   slug: "f-link"